
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake-4.3/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/home/louai/.local/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/usr/games/"
      - "/usr/local/games/"
      - "/usr/lib/wsl/lib/"
      - "/mnt/c/Python313/Scripts/"
      - "/mnt/c/Python313/"
      - "/mnt/c/Program Files/Eclipse Adoptium/jdk-21.0.3.9-hotspot/bin/"
      - "/mnt/c/Program Files/Microsoft/jdk-11.0.16.101-hotspot/bin/"
      - "/mnt/c/WINDOWS/system32/"
      - "/mnt/c/WINDOWS/"
      - "/mnt/c/WINDOWS/System32/Wbem/"
      - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
      - "/mnt/c/WINDOWS/System32/OpenSSH/"
      - "/mnt/c/Program Files (x86)/PharosSystems/Core/"
      - "/mnt/c/Program Files/Microsoft SQL Server/120/Tools/Binn/"
      - "/mnt/c/Program Files/Common Files/Autodesk Shared/"
      - "/mnt/c/Program Files/dotnet/"
      - "/mnt/c/Program Files/Git/cmd/"
      - "/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "/mnt/c/Program Files/GitHub CLI/"
      - "/mnt/c/ProgramData/chocolatey/bin/"
      - "/mnt/c/Users/princ/AppData/Local/nvm/"
      - "/mnt/c/nvm4w/nodejs/"
      - "/mnt/c/Program Files/PuTTY/"
      - "/mnt/c/Users/princ/AppData/Local/Programs/cursor/resources/app/bin/"
      - "/mnt/c/Program Files/cursor/resources/app/bin/"
      - "/mnt/c/Program Files (x86)/cloudflared/"
      - "/mnt/c/Program Files/PowerShell/7/"
      - "/mnt/c/Program Files/usbipd-win/"
      - "/mnt/c/Users/princ/AppData/Local/Programs/Python/Python310/Scripts/"
      - "/mnt/c/Users/princ/AppData/Local/Programs/Python/Python310/"
      - "/mnt/c/Users/princ/AppData/Local/Microsoft/WindowsApps/"
      - "/mnt/c/Program Files/JetBrains/PyCharm Community Edition 2022.2.1/bin/"
      - "/mnt/c/Users/princ/AppData/Local/GitHubDesktop/bin/"
      - "/mnt/c/msys64/ucrt64/bin/"
      - "/mnt/c/Users/princ/.dotnet/tools/"
      - "/mnt/c/Program Files/Git/bin/"
      - "/mnt/c/Users/princ/Downloads/ookla-speedtest/"
      - "/mnt/c/Program Files/JetBrains/CLion 2024.2.3/bin/"
      - "/mnt/c/Program Files/JetBrains/PyCharm 2024.2.4/bin/"
      - "/mnt/c/Program Files (x86)/Nmap/"
      - "/mnt/c/Users/princ/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "/mnt/c/Users/princ/AppData/Roaming/npm/"
      - "/mnt/c/Users/princ/AppData/Local/Microsoft/WinGet/Packages/Genymobile.scrcpy_Microsoft.Winget.Source_8wekyb3d8bbwe/scrcpy-win64-v3.1/"
      - "/mnt/c/Users/princ/AppData/Local/Microsoft/WinGet/Packages/Google.PlatformTools_Microsoft.Winget.Source_8wekyb3d8bbwe/platform-tools/"
      - "/mnt/c/nvm4w/nodejs/node_modules/npm/bin/node-gyp-bin/"
      - "/mnt/c/Users/princ/AppData/Local/Microsoft/WinGet/Packages/Typst.Typst_Microsoft.Winget.Source_8wekyb3d8bbwe/typst-x86_64-pc-windows-msvc/"
      - "/mnt/c/Users/princ/AppData/Roaming/Python/Python313/Scripts/"
      - "/mnt/c/Users/princ/AppData/Local/PowerToys/DSCModules/"
      - "/mnt/c/Users/princ/AppData/Local/Microsoft/WinGet/Packages/DenoLand.Deno_Microsoft.Winget.Source_8wekyb3d8bbwe/"
      - "/mnt/c/Users/princ/AppData/Local/Microsoft/WinGet/Packages/yt-dlp.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe/ffmpeg-N-122609-g364d5dda91-win64-gpl/bin/"
      - "/mnt/c/Users/princ/AppData/Local/Microsoft/WinGet/Packages/yt-dlp.yt-dlp_Microsoft.Winget.Source_8wekyb3d8bbwe/"
      - "/snap/bin/"
    searched_directories:
      - "/home/louai/.local/bin/uname"
      - "/usr/local/sbin/uname"
      - "/usr/local/bin/uname"
      - "/usr/sbin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/home/louai/.local/bin"
        - "/home/louai/.local/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/usr/games"
        - "/usr/local/games"
        - "/usr/lib/wsl/lib"
        - "/mnt/c/Python313/Scripts/"
        - "/mnt/c/Python313/"
        - "/mnt/c/Program Files/Eclipse Adoptium/jdk-21.0.3.9-hotspot/bin"
        - "/mnt/c/Program Files/Microsoft/jdk-11.0.16.101-hotspot/bin"
        - "/mnt/c/WINDOWS/system32"
        - "/mnt/c/WINDOWS"
        - "/mnt/c/WINDOWS/System32/Wbem"
        - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
        - "/mnt/c/WINDOWS/System32/OpenSSH/"
        - "/mnt/c/Program Files (x86)/PharosSystems/Core"
        - "/mnt/c/Program Files/Microsoft SQL Server/120/Tools/Binn/"
        - "/mnt/c/Program Files/Common Files/Autodesk Shared/"
        - "/mnt/c/Program Files/dotnet/"
        - "/mnt/c/Program Files/Git/cmd"
        - "/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
        - "/mnt/c/Program Files/GitHub CLI/"
        - "/mnt/c/ProgramData/chocolatey/bin"
        - "/mnt/c/WINDOWS/system32"
        - "/mnt/c/WINDOWS"
        - "/mnt/c/WINDOWS/System32/Wbem"
        - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
        - "/mnt/c/WINDOWS/System32/OpenSSH/"
        - "/mnt/c/Users/princ/AppData/Local/nvm"
        - "/mnt/c/nvm4w/nodejs"
        - "/mnt/c/Program Files/PuTTY/"
        - "/mnt/c/Users/princ/AppData/Local/Programs/cursor/resources/app/bin"
        - "/mnt/c/Users/princ/AppData/Local/Programs/cursor/resources/app/bin"
        - "/mnt/c/Program Files/cursor/resources/app/bin"
        - "/mnt/c/Program Files (x86)/cloudflared/"
        - "/mnt/c/Program Files/PowerShell/7/"
        - "/mnt/c/Program Files/usbipd-win/"
        - "/mnt/c/Users/princ/AppData/Local/Programs/Python/Python310/Scripts/"
        - "/mnt/c/Users/princ/AppData/Local/Programs/Python/Python310/"
        - "/mnt/c/Users/princ/AppData/Local/Microsoft/WindowsApps"
        - "/mnt/c/Program Files/JetBrains/PyCharm Community Edition 2022.2.1/bin"
        - "/mnt/c/Users/princ/AppData/Local/GitHubDesktop/bin"
        - "/mnt/c/msys64/ucrt64/bin"
        - "/mnt/c/Users/princ/.dotnet/tools"
        - "/mnt/c/Program Files/Git/bin"
        - "/mnt/c/Users/princ/Downloads/ookla-speedtest"
        - "/mnt/c/Program Files/JetBrains/CLion 2024.2.3/bin"
        - "/mnt/c/Program Files/JetBrains/PyCharm 2024.2.4/bin"
        - "/mnt/c/Program Files (x86)/Nmap"
        - "/mnt/c/Users/princ/AppData/Local/Programs/Microsoft VS Code/bin"
        - "/mnt/c/Users/princ/AppData/Roaming/npm"
        - "/mnt/c/Users/princ/AppData/Local/Microsoft/WinGet/Packages/Genymobile.scrcpy_Microsoft.Winget.Source_8wekyb3d8bbwe/scrcpy-win64-v3.1"
        - "/mnt/c/Users/princ/AppData/Local/Microsoft/WinGet/Packages/Google.PlatformTools_Microsoft.Winget.Source_8wekyb3d8bbwe/platform-tools"
        - "/mnt/c/Users/princ/AppData/Local/nvm"
        - "/mnt/c/nvm4w/nodejs"
        - "/mnt/c/nvm4w/nodejs/node_modules/npm/bin/node-gyp-bin"
        - "/mnt/c/Users/princ/AppData/Local/Programs/cursor/resources/app/bin"
        - "/mnt/c/Users/princ/AppData/Local/Microsoft/WinGet/Packages/Typst.Typst_Microsoft.Winget.Source_8wekyb3d8bbwe/typst-x86_64-pc-windows-msvc"
        - "/mnt/c/Users/princ/AppData/Roaming/Python/Python313/Scripts"
        - "/mnt/c/Users/princ/AppData/Local/PowerToys/DSCModules/"
        - "/mnt/c/Users/princ/AppData/Local/Microsoft/WinGet/Packages/DenoLand.Deno_Microsoft.Winget.Source_8wekyb3d8bbwe"
        - "/mnt/c/Users/princ/AppData/Local/Microsoft/WinGet/Packages/yt-dlp.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe/ffmpeg-N-122609-g364d5dda91-win64-gpl/bin"
        - "/mnt/c/Users/princ/AppData/Local/Microsoft/WinGet/Packages/yt-dlp.yt-dlp_Microsoft.Winget.Source_8wekyb3d8bbwe"
        - "/snap/bin"
        - "/snap/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-4.3/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.6.87.2-microsoft-standard-WSL2 - x86_64
  -
    kind: "find-v1"
    backtrace:
      - "/usr/share/cmake-4.3/Modules/CMakeUnixFindMake.cmake:5 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_MAKE_PROGRAM"
    description: "Path to a program."
    settings:
      SearchFramework: "NEVER"
      SearchAppBundle: "NEVER"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "gmake"
      - "make"
      - "smake"
    candidate_directories:
      - "/home/louai/.local/bin/"
      - "/usr/local/sbin/"
      - "/usr/local/bin/"
      - "/usr/sbin/"
      - "/usr/bin/"
      - "/sbin/"
      - "/bin/"
      - "/usr/games/"
      - "/usr/local/games/"
      - "/usr/lib/wsl/lib/"
      - "/mnt/c/Python313/Scripts/"
      - "/mnt/c/Python313/"
      - "/mnt/c/Program Files/Eclipse Adoptium/jdk-21.0.3.9-hotspot/bin/"
      - "/mnt/c/Program Files/Microsoft/jdk-11.0.16.101-hotspot/bin/"
      - "/mnt/c/WINDOWS/system32/"
      - "/mnt/c/WINDOWS/"
      - "/mnt/c/WINDOWS/System32/Wbem/"
      - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
      - "/mnt/c/WINDOWS/System32/OpenSSH/"
      - "/mnt/c/Program Files (x86)/PharosSystems/Core/"
      - "/mnt/c/Program Files/Microsoft SQL Server/120/Tools/Binn/"
      - "/mnt/c/Program Files/Common Files/Autodesk Shared/"
      - "/mnt/c/Program Files/dotnet/"
      - "/mnt/c/Program Files/Git/cmd/"
      - "/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
      - "/mnt/c/Program Files/GitHub CLI/"
      - "/mnt/c/ProgramData/chocolatey/bin/"
      - "/mnt/c/Users/princ/AppData/Local/nvm/"
      - "/mnt/c/nvm4w/nodejs/"
      - "/mnt/c/Program Files/PuTTY/"
      - "/mnt/c/Users/princ/AppData/Local/Programs/cursor/resources/app/bin/"
      - "/mnt/c/Program Files/cursor/resources/app/bin/"
      - "/mnt/c/Program Files (x86)/cloudflared/"
      - "/mnt/c/Program Files/PowerShell/7/"
      - "/mnt/c/Program Files/usbipd-win/"
      - "/mnt/c/Users/princ/AppData/Local/Programs/Python/Python310/Scripts/"
      - "/mnt/c/Users/princ/AppData/Local/Programs/Python/Python310/"
      - "/mnt/c/Users/princ/AppData/Local/Microsoft/WindowsApps/"
      - "/mnt/c/Program Files/JetBrains/PyCharm Community Edition 2022.2.1/bin/"
      - "/mnt/c/Users/princ/AppData/Local/GitHubDesktop/bin/"
      - "/mnt/c/msys64/ucrt64/bin/"
      - "/mnt/c/Users/princ/.dotnet/tools/"
      - "/mnt/c/Program Files/Git/bin/"
      - "/mnt/c/Users/princ/Downloads/ookla-speedtest/"
      - "/mnt/c/Program Files/JetBrains/CLion 2024.2.3/bin/"
      - "/mnt/c/Program Files/JetBrains/PyCharm 2024.2.4/bin/"
      - "/mnt/c/Program Files (x86)/Nmap/"
      - "/mnt/c/Users/princ/AppData/Local/Programs/Microsoft VS Code/bin/"
      - "/mnt/c/Users/princ/AppData/Roaming/npm/"
      - "/mnt/c/Users/princ/AppData/Local/Microsoft/WinGet/Packages/Genymobile.scrcpy_Microsoft.Winget.Source_8wekyb3d8bbwe/scrcpy-win64-v3.1/"
      - "/mnt/c/Users/princ/AppData/Local/Microsoft/WinGet/Packages/Google.PlatformTools_Microsoft.Winget.Source_8wekyb3d8bbwe/platform-tools/"
      - "/mnt/c/nvm4w/nodejs/node_modules/npm/bin/node-gyp-bin/"
      - "/mnt/c/Users/princ/AppData/Local/Microsoft/WinGet/Packages/Typst.Typst_Microsoft.Winget.Source_8wekyb3d8bbwe/typst-x86_64-pc-windows-msvc/"
      - "/mnt/c/Users/princ/AppData/Roaming/Python/Python313/Scripts/"
      - "/mnt/c/Users/princ/AppData/Local/PowerToys/DSCModules/"
      - "/mnt/c/Users/princ/AppData/Local/Microsoft/WinGet/Packages/DenoLand.Deno_Microsoft.Winget.Source_8wekyb3d8bbwe/"
      - "/mnt/c/Users/princ/AppData/Local/Microsoft/WinGet/Packages/yt-dlp.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe/ffmpeg-N-122609-g364d5dda91-win64-gpl/bin/"
      - "/mnt/c/Users/princ/AppData/Local/Microsoft/WinGet/Packages/yt-dlp.yt-dlp_Microsoft.Winget.Source_8wekyb3d8bbwe/"
      - "/snap/bin/"
    searched_directories:
      - "/home/louai/.local/bin/gmake"
      - "/usr/local/sbin/gmake"
      - "/usr/local/bin/gmake"
      - "/usr/sbin/gmake"
    found: "/usr/bin/gmake"
    search_context:
      ENV{PATH}:
        - "/home/louai/.local/bin"
        - "/home/louai/.local/bin"
        - "/usr/local/sbin"
        - "/usr/local/bin"
        - "/usr/sbin"
        - "/usr/bin"
        - "/sbin"
        - "/bin"
        - "/usr/games"
        - "/usr/local/games"
        - "/usr/lib/wsl/lib"
        - "/mnt/c/Python313/Scripts/"
        - "/mnt/c/Python313/"
        - "/mnt/c/Program Files/Eclipse Adoptium/jdk-21.0.3.9-hotspot/bin"
        - "/mnt/c/Program Files/Microsoft/jdk-11.0.16.101-hotspot/bin"
        - "/mnt/c/WINDOWS/system32"
        - "/mnt/c/WINDOWS"
        - "/mnt/c/WINDOWS/System32/Wbem"
        - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
        - "/mnt/c/WINDOWS/System32/OpenSSH/"
        - "/mnt/c/Program Files (x86)/PharosSystems/Core"
        - "/mnt/c/Program Files/Microsoft SQL Server/120/Tools/Binn/"
        - "/mnt/c/Program Files/Common Files/Autodesk Shared/"
        - "/mnt/c/Program Files/dotnet/"
        - "/mnt/c/Program Files/Git/cmd"
        - "/mnt/c/Program Files (x86)/Windows Kits/10/Windows Performance Toolkit/"
        - "/mnt/c/Program Files/GitHub CLI/"
        - "/mnt/c/ProgramData/chocolatey/bin"
        - "/mnt/c/WINDOWS/system32"
        - "/mnt/c/WINDOWS"
        - "/mnt/c/WINDOWS/System32/Wbem"
        - "/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/"
        - "/mnt/c/WINDOWS/System32/OpenSSH/"
        - "/mnt/c/Users/princ/AppData/Local/nvm"
        - "/mnt/c/nvm4w/nodejs"
        - "/mnt/c/Program Files/PuTTY/"
        - "/mnt/c/Users/princ/AppData/Local/Programs/cursor/resources/app/bin"
        - "/mnt/c/Users/princ/AppData/Local/Programs/cursor/resources/app/bin"
        - "/mnt/c/Program Files/cursor/resources/app/bin"
        - "/mnt/c/Program Files (x86)/cloudflared/"
        - "/mnt/c/Program Files/PowerShell/7/"
        - "/mnt/c/Program Files/usbipd-win/"
        - "/mnt/c/Users/princ/AppData/Local/Programs/Python/Python310/Scripts/"
        - "/mnt/c/Users/princ/AppData/Local/Programs/Python/Python310/"
        - "/mnt/c/Users/princ/AppData/Local/Microsoft/WindowsApps"
        - "/mnt/c/Program Files/JetBrains/PyCharm Community Edition 2022.2.1/bin"
        - "/mnt/c/Users/princ/AppData/Local/GitHubDesktop/bin"
        - "/mnt/c/msys64/ucrt64/bin"
        - "/mnt/c/Users/princ/.dotnet/tools"
        - "/mnt/c/Program Files/Git/bin"
        - "/mnt/c/Users/princ/Downloads/ookla-speedtest"
        - "/mnt/c/Program Files/JetBrains/CLion 2024.2.3/bin"
        - "/mnt/c/Program Files/JetBrains/PyCharm 2024.2.4/bin"
        - "/mnt/c/Program Files (x86)/Nmap"
        - "/mnt/c/Users/princ/AppData/Local/Programs/Microsoft VS Code/bin"
        - "/mnt/c/Users/princ/AppData/Roaming/npm"
        - "/mnt/c/Users/princ/AppData/Local/Microsoft/WinGet/Packages/Genymobile.scrcpy_Microsoft.Winget.Source_8wekyb3d8bbwe/scrcpy-win64-v3.1"
        - "/mnt/c/Users/princ/AppData/Local/Microsoft/WinGet/Packages/Google.PlatformTools_Microsoft.Winget.Source_8wekyb3d8bbwe/platform-tools"
        - "/mnt/c/Users/princ/AppData/Local/nvm"
        - "/mnt/c/nvm4w/nodejs"
        - "/mnt/c/nvm4w/nodejs/node_modules/npm/bin/node-gyp-bin"
        - "/mnt/c/Users/princ/AppData/Local/Programs/cursor/resources/app/bin"
        - "/mnt/c/Users/princ/AppData/Local/Microsoft/WinGet/Packages/Typst.Typst_Microsoft.Winget.Source_8wekyb3d8bbwe/typst-x86_64-pc-windows-msvc"
        - "/mnt/c/Users/princ/AppData/Roaming/Python/Python313/Scripts"
        - "/mnt/c/Users/princ/AppData/Local/PowerToys/DSCModules/"
        - "/mnt/c/Users/princ/AppData/Local/Microsoft/WinGet/Packages/DenoLand.Deno_Microsoft.Winget.Source_8wekyb3d8bbwe"
        - "/mnt/c/Users/princ/AppData/Local/Microsoft/WinGet/Packages/yt-dlp.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe/ffmpeg-N-122609-g364d5dda91-win64-gpl/bin"
        - "/mnt/c/Users/princ/AppData/Local/Microsoft/WinGet/Packages/yt-dlp.yt-dlp_Microsoft.Winget.Source_8wekyb3d8bbwe"
        - "/snap/bin"
        - "/snap/bin"
...
